from __future__ import annotations

import asyncio
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from typing import Literal

from pydantic import BaseModel, Field
from mcp.server import MCPServer
from mcp.server.mcpserver.context import Context
from mcp.server.mcpserver.exceptions import ToolError

from mcp_anythingllm import __version__
from mcp_anythingllm.anythingllm import AnythingLLMClient, AnythingLLMError
from mcp_anythingllm.config import Config

VALID_MODES = Literal["query", "chat", "automatic"]


class SourceItem(BaseModel):
    """One retrieved context chunk used in the answer."""

    title: str
    chunk: str


class AskResult(BaseModel):
    """Answer generated by AnythingLLM for the workspace, with its sources."""

    answer: str
    sources: list[SourceItem] = []
    mode: str
    workspace: str


@dataclass
class _State:
    client: AnythingLLMClient
    slug: str | None = None
    lock: asyncio.Lock = field(default_factory=asyncio.Lock)


def create_server(cfg: Config) -> MCPServer:
    @asynccontextmanager
    async def lifespan(server: MCPServer):
        client = AnythingLLMClient(cfg.base_url, cfg.api_key, timeout=cfg.request_timeout)
        server._anything_llm_state = _State(client=client)
        try:
            yield
        finally:
            await client.close()

    mcp = MCPServer(
        name="anythingllm",
        title="AnythingLLM",
        version=__version__,
        description="Ask questions against a local AnythingLLM workspace and get AI answers grounded in its documents.",
        instructions=(
            "This server exposes the single AnythingLLM workspace configured at startup. "
            "Use the ask_workspace tool. The default mode 'query' answers strictly from "
            "workspace documents (no general knowledge); 'chat' also mixes in model "
            "general knowledge; 'automatic' uses native tool calling when the provider "
            "supports it."
        ),
        lifespan=lifespan,
        dependencies=["httpx", "python-dotenv"],
    )

    @mcp.tool(
        name="ask_workspace",
        title="Ask the AnythingLLM workspace",
        description=(
            "Ask a question and receive an AI answer generated from the knowledge base "
            "of the single AnythingLLM workspace, along with the document chunks that "
            "were used as context. Use this when the user asks about content stored in "
            "the workspace."
        ),
    )
    async def ask_workspace(
        message: str = Field(description="The question to ask the workspace."),
        mode: VALID_MODES = Field(
            default=cfg.default_mode,
            description=(
                "How to answer. query: strict retrieval, only answers when the workspace "
                "has relevant context. chat: uses model general knowledge plus workspace "
                "embeddings. automatic: native tool calling if the provider supports it."
            ),
        ),
        top_n: int | None = Field(
            default=cfg.default_top_n,
            ge=1,
            le=20,
            description="Number of context chunks to retrieve (optional).",
        ),
        similarity_threshold: float | None = Field(
            default=cfg.default_similarity_threshold,
            ge=0.0,
            le=1.0,
            description="Minimum vector similarity for a chunk to be used (optional).",
        ),
        ctx: Context | None = None,
    ) -> AskResult:
        if ctx is None:
            raise ToolError("Context unavailable for this request.")
        state: _State = ctx.mcp_server._anything_llm_state
        slug = await _resolve_workspace_slug(state, cfg)
        try:
            result = await state.client.chat(
                slug,
                message,
                mode=mode,
                top_n=top_n if top_n is not None else cfg.default_top_n,
                similarity_threshold=similarity_threshold
                if similarity_threshold is not None
                else cfg.default_similarity_threshold,
            )
        except AnythingLLMError as exc:
            raise ToolError(str(exc)) from exc

        if result.error:
            raise ToolError(f"AnythingLLM reported an error for this query: {result.error}")
        if not result.text_response and not result.sources:
            raise ToolError(
                "AnythingLLM returned no answer and no sources for this question. "
                "The workspace likely has no relevant context."
            )

        return AskResult(
            answer=result.text_response,
            sources=[SourceItem(title=source.title, chunk=source.chunk) for source in result.sources],
            mode=mode,
            workspace=slug,
        )

    return mcp


async def _resolve_workspace_slug(state: _State, cfg: Config) -> str:
    if state.slug is not None:
        return state.slug
    async with state.lock:
        if state.slug is not None:
            return state.slug
        if cfg.workspace_slug:
            try:
                await state.client.get_workspace(cfg.workspace_slug)
            except AnythingLLMError:
                raise
            state.slug = cfg.workspace_slug
            return state.slug

        workspaces = await state.client.list_workspaces()
        if len(workspaces) == 1:
            state.slug = str(workspaces[0]["slug"])
            return state.slug
        if not workspaces:
            raise ToolError(
                "No workspace is available in AnythingLLM. Create one first, then retry."
            )
        names = ", ".join(str(ws.get("name")) for ws in workspaces)
        raise ToolError(
            f"AnythingLLM has {len(workspaces)} workspaces ({names}). Set "
            "ALLM_WORKSPACE_SLUG in the .env to select the workspace."
        )